### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by simwai** [cottand/leng#72]
Heyo,

I really like this project. I have set it up today in 3 hours with docker-compose, and it is super cool. The only thing I miss is a whitelist functionality to be able to use whitelists addtionally to blocklists.
I guess why that makes sense is obvious.

Best regards,
simwai

**Comment by cottand** [comment]
Glad you like leng!

Did you try the config `Blocking.whitelist`? Or are you looking for something else?

For example:
```toml
[Blocking]
    # comment for reference
    whitelist = [
        # "getsentry.com",
    ]
```
